### ISSUE TITLE
brat styles corrupt svg display

### ISSUE THREAD

**Issue by antonkulaga** [nlplab/brat#1182]
In brat styles are changed for all svg-s
```css
svg {
  width: 100%;
  height: 1px;
  border: 1px solid #7fa2ff;
  font-size: 15px;
  /* font-size: 14px; */
}
```
It breaks layout of other libs/html when brat is embedded to the page as it affects all svgs (even outside brat annotations)
